# This rule is not used by the project kubearchive-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the kubearchive.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubearchive-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubearchiveinstallation-editor-role
rules:
- apiGroups:
  - kubearchive.org
  resources:
  - kubearchiveinstallations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubearchive.org
  resources:
  - kubearchiveinstallations/status
  verbs:
  - get
