---
apiVersion: kubearchive.org/v1
kind: KubeArchiveInstallation
metadata:
  labels:
    app.kubernetes.io/name: kubearchive-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubearchiveinstallation-sample
spec:
  version: v1.17.2
